spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/workshop_todo;MODE=MySQL;
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret-key: WORKSHOP6349
    
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
